### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by Pullal0215** [wvega/timepicker#63]
Hi wvega,

Please let me know if you are planning for a new release...?

Regards,
Pratap Ullal

**Comment by Rishi1600** [comment]
Hi wvega, 

The fix for #56 seems to work. Is V1.3.3 ready yet? 

Thanks 
Rishi

**Comment by wvega** [comment]
More than a year later, but [jQuery Timepicker 1.3.3](https://github.com/wvega/timepicker/releases/tag/1.3.3) is ready now. Thank you!
