### ISSUE TITLE
Typo at http://timepicker.co/options/

### ISSUE THREAD

**Issue by cvandermeer** [wvega/timepicker#64]
24 hour without leadgin 0.

**Comment by cvandermeer** [comment]
![screen shot 2015-01-20 at 1 49 51 pm](https://cloud.githubusercontent.com/assets/5426992/5817355/4764474e-a0ab-11e4-98a3-c0aff7ba5ef2.png)

**Comment by wvega** [comment]
@cvandermeer, thank you for taking the time to report this. The commit above fixes that problem.

![jquery_timepicker_options](https://cloud.githubusercontent.com/assets/45068/5819362/32d99952-a08b-11e4-9b14-35192c37fe13.png)
