### ISSUE TITLE
Requiring in NPM/Browserify

### ISSUE THREAD

**Issue by webkenny** [wvega/timepicker#75]
Hi there,

I am willing to help write the README instructions for this, but how would one go about requiring this in a npm (e.g. browserify) type project? Is that not currently supported?

I ask because I did install with npm but then when including it via `require('jquery-timepicker')` the application throws an error saying it cannot find it.

My assumption being that it can be installed with NPM is that it would be able to be included in the traditional node manner. Truth?

If not, I am happy to write the patch to do so.

P.S. It might be helpful for you to know I am using this in Laravel which is a gulp based environment.

**Comment by wvega** [comment]
Hi @webkenny,

>My assumption being that it can be installed with NPM is that it would be able to be included in the traditional node manner. Truth?

Unfortunately, I think including the plugin in the traditional node manner doesn't work right now. 

I moved the plugin to npm when jQuery Plugins shutdown and recommended using npm as the new distribution channel.

Your assumption is a valid one, though. The plugin should support it!. So I'd really appreciate a patch to fix this.

>P.S. It might be helpful for you to know I am using this in Laravel which is a gulp based environment.

Thanks for that! I'll try to take a look at using the plugin in a Laravel environment to understand this issue better.

--

If I'm getting this correct, you don't need to use anything from the plugin in a node app, you just want to be able to install the plugin using npm and use it in the browser, after you have created a bundle with Browserify. Is that right?

**Comment by webkenny** [comment]
Thanks for the quick reply! Exactly right on your final comment. That's all I really want is to use it via browserify.

**Comment by wvega** [comment]
@webkenny could you please try jQuery Timepicker 1.3.4. You should be able to use it with Browserify without issues. Thanks for reporting this!
