### ISSUE TITLE
Can not show all view

### ISSUE THREAD

**Issue by zouwei1991** [wvega/timepicker#77]
it cannot show all it's view ,hiden by another div element
how to upload an image?
![Uploading QQ截图20160622122153.png…]()

**Comment by wvega** [comment]
@zouwei1991 you screenshot was not uploaded properly. Could you please try that again?

**Comment by wvega** [comment]
@zouwei1991 You can upload the image just by dragging it to the text area, but you need to wait until the upload completes. Use the **Preview** tab to confirm the image was uploaded and shows up properly.

**Comment by zouwei1991** [comment]
![qq 20160622122153](https://cloud.githubusercontent.com/assets/19298694/16255457/80a4d3ba-387c-11e6-8208-b9ba3ef4ce9a.png)

ok. if the image is uploaded successfully,as seen in the image,part of the timepicker is hidden by my div
element,and I have no idea how to resolve it

**Comment by wvega** [comment]
@zouwei1991 The problem here seems to be the dialog's DIV has a greater value for the `z-index` property. Fortunately, I think there is an option that may help you: `zindex`.

Set it to a non-null value and the element displaying the timepicker will use that.

```javascript
$('timepicker').timepicker({
    // ... your other options
    zindex: 100 // make sure this value is greater than the value used by the DIV
});
```

**Comment by zouwei1991** [comment]
Thank you!

**Comment by wvega** [comment]
You're welcome!
