### ISSUE TITLE
Custom formatting does not prevent AM and PM designators

### ISSUE THREAD

**Issue by sonergonul** [wvega/timepicker#85]
Hello

I created this timepicker with `HH:mm`custom format in `timeformat`. Here is my sample code:

```
<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.css"/>
<script src="http://cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.js"></script>
```

and

```
$(document).ready(function () {
   $('input.timepicker').timepicker({
       timeformat: 'HH:mm'
       });
});
```

and

`<input type="text" name="timepicker1" class="timepicker"/>`

But this picker _still_ shows designators _even_ I formatted it as custom.

![image](https://cloud.githubusercontent.com/assets/1696649/19379832/bd984598-91fc-11e6-8a0e-612887358bed.png)

Google Chrome 53.0.2785.143 m (64-bit)
Internet Explorer 11.0.9600.18230
Firefox 49.0.1

Here is JSFiddle example: http://jsfiddle.net/18vwvy66/

But _why_? Isn't that custom format (`timeformat`) is for? Is there any way to prevent these designators?

**Comment by wvega** [comment]
Hi @sonergonul. Setting names are case-sensitive; you should use `timeFormat` instead.

**Comment by sonergonul** [comment]
@wvega Oh, I'm deeply sorry about that. Looks like I wrote it _myself_ since Visual Studio doesn't suggest any result when I start typing as intellisense. Just a silly mistake.

**Comment by wvega** [comment]
@sonergonul no worries ;)
